export const TestingFakeLawyers = [
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
  {
    name: "Sarah Johnson",
    specialty: ["Corporate Law", "Intellectual Property", "Contract Law", "Employment Law", "Real Estate Law"],
    rating: 4.9,
    reviewCount: 197,
    hourlyRate: [230, 450, 350, 400, 300],
    // statusText: "Available Today",
    // yearsExperience: 12,
  },
  {
    name: "Michael Chen",
    specialty: ["Family Law"],
    rating: 4.8,
    reviewCount: 205,
    hourlyRate: [300],
    // statusText: "Available Today",
    // yearsExperience: 16,
  },
  {
    name: "Emily Rodriguez",
    specialty: ["Criminal Defense", "Civil Rights", "Personal Injury"],
    rating: 4.9,
    reviewCount: 189,
    hourlyRate: [375, 400, 350],
    // statusText: "Available Today",
  },
];
