export const TestingFakeLawyers = [
  {
    name: "Баярсайхан Дорж",
    specialty: ["Компанийн эрх зүй", "Гэрээний эрх зүй", "Эд хөрөнгийн эрх зүй"],
    rating: 4.8,
    reviewCount: 215,
    hourlyRate: [350000, 300000, 320000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 15,
  },
  {
    name: "Энхтуяа Батбаяр",
    specialty: ["Гэр бүлийн хууль", "Өв залгамжлал", "Хэрэглэгчийн эрх ашгийг хамгаалах"],
    rating: 4.9,
    reviewCount: 180,
    hourlyRate: [280000, 250000, 270000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 10,
  },
  {
    name: "Ганзориг Сүхбаатар",
    specialty: ["Эрүүгийн хууль", "Иргэний хууль", "Зөрчлийн хууль"],
    rating: 4.7,
    reviewCount: 155,
    hourlyRate: [400000, 380000, 390000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 18,
  },
  {
    name: "Оюунчимэг Цэрэндорж",
    specialty: ["Хөдөлмөрийн хууль", "Оюуны өмч", "Захиргааны эрх зүй"],
    rating: 4.9,
    reviewCount: 230,
    hourlyRate: [320000, 360000, 340000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 14,
  },
  {
    name: "Мөнхбат Цолмон",
    specialty: ["Уул уурхайн эрх зүй", "Байгаль орчны эрх зүй", "Концесс, PPP эрх зүй"],
    rating: 4.8,
    reviewCount: 190,
    hourlyRate: [450000, 420000, 480000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 20,
  },
  {
    name: "Алтанцэцэг Бат-Эрдэнэ",
    specialty: ["Банк, санхүүгийн эрх зүй", "Татварын хууль", "Даатгалын эрх зүй"],
    rating: 4.7,
    reviewCount: 170,
    hourlyRate: [370000, 330000, 350000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 11,
  },
  {
    name: "Уранчимэг Ганболд",
    specialty: ["Хөрөнгө оруулалтын эрх зүй", "Аж ахуйн нэгжийн эрх зүй", "Олон улсын эрх зүй"],
    rating: 4.9,
    reviewCount: 200,
    hourlyRate: [430000, 390000, 450000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 16,
  },
  {
    name: "Төмөрбаатар Жаргалсайхан",
    specialty: ["Худалдааны эрх зүй", "Маргаан шийдвэрлэх", "Банкрот буюу дампуурлын эрх зүй"],
    rating: 4.8,
    reviewCount: 195,
    hourlyRate: [380000, 410000, 400000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 13,
  },
  {
    name: "Дэлгэрмаа Энхбаяр",
    specialty: ["Эмнэлгийн эрх зүй", "Боловсролын эрх зүй", "Зөрчлийн хууль"],
    rating: 4.6,
    reviewCount: 140,
    hourlyRate: [300000, 290000, 310000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 9,
  },
  {
    name: "Эрдэнэбаяр Нямдорж",
    specialty: ["Хэрэглэгчийн эрх ашгийг хамгаалах", "Гэмт хэргийн хохирогчид", "Иргэний хууль"],
    rating: 4.7,
    reviewCount: 165,
    hourlyRate: [340000, 310000, 330000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 10,
  },

  {
    name: "Цэрэндолгор Батжаргал",
    specialty: ["Газар зохион байгуулалт", "Эд хөрөнгийн эрх зүй", "Байгаль орчны эрх зүй"],
    rating: 4.5,
    reviewCount: 130,
    hourlyRate: [360000, 340000, 370000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 12,
  },
  {
    name: "Давааням Бумбаяр",
    specialty: ["Үндсэн хуулийн эрх зүй", "Захиргааны эрх зүй", "Олон улсын эрх зүй"],
    rating: 4.7,
    reviewCount: 188,
    hourlyRate: [400000, 390000, 420000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 17,
  },
  {
    name: "Энхжаргал Доржпалам",
    specialty: ["Кибер аюулгүй байдал, мэдээллийн технологи", "Оюуны өмч", "Компанийн эрх зүй"],
    rating: 4.9,
    reviewCount: 240,
    hourlyRate: [480000, 450000, 430000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 19,
  },
  {
    name: "Болдбаатар Самдан",
    specialty: ["Банкрот буюу дампуурлын эрх зүй", "Татварын хууль", "Худалдааны эрх зүй"],
    rating: 4.6,
    reviewCount: 160,
    hourlyRate: [390000, 360000, 370000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 14,
  },
  {
    name: "Мөнхсайхан Энхбаатар",
    specialty: ["Спортын эрх зүй", "Хөдөлмөрийн хууль", "Гэрээний эрх зүй"],
    rating: 4.5,
    reviewCount: 110,
    hourlyRate: [320000, 300000, 310000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 8,
  },
  {
    name: "Хулан Цогбаяр",
    specialty: ["Үнэт цаасны эрх зүй", "Банк, санхүүгийн эрх зүй", "Хөрөнгө оруулалтын эрх зүй"],
    rating: 4.8,
    reviewCount: 199,
    hourlyRate: [460000, 440000, 470000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 16,
  },
  {
    name: "Энхмаа Чулуунбаатар",
    specialty: ["Эрүүл мэндийн эрх зүй", "Боловсролын эрх зүй", "Зөрчлийн хууль"],
    rating: 4.7,
    reviewCount: 150,
    hourlyRate: [330000, 310000, 300000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 11,
  },
  {
    name: "Гансүх Наранбаатар",
    specialty: ["Эрүүгийн хууль", "Хэрэглэгчийн эрх ашгийг хамгаалах", "Даатгалын эрх зүй"],
    rating: 4.6,
    reviewCount: 145,
    hourlyRate: [380000, 320000, 350000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 13,
  },
  {
    name: "Мандах Гантулга",
    specialty: ["Компанийн эрх зүй", "Оюуны өмч", "Кибер аюулгүй байдал, мэдээллийн технологи"],
    rating: 4.9,
    reviewCount: 225,
    hourlyRate: [440000, 420000, 460000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 17,
  },
  {
    name: "Батцэцэг Отгонбаатар",
    specialty: ["Гэр бүлийн хууль", "Эд хөрөнгийн эрх зүй", "Захиргааны эрх зүй"],
    rating: 4.8,
    reviewCount: 178,
    hourlyRate: [290000, 310000, 330000],
    statusText: "Өнөөдөр боломжтой",
    yearsExperience: 10,
  },
];
